apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodatabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongod
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongod
    spec:
      volumes:
      - name: task-pv-local
        persistentVolumeClaim:
          claimName: task-pv-claim
      containers:
      - name: mongodatabase
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: task-pv-local
        env:
        - name: mongo-root-username
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: mongo-root-password
          valueFrom: 
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_PASSWORD
