apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-pod
  labels: 
    app: myapp
spec:
  selector: 
    matchLabels:
      app: student
  replicas: 1
  template:
    metadata:
      name: myapp-pod
      labels:
        app: student
    spec:
      containers:
      - name: studentapp
        imagePullPolicy: Never
        image: student
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 8000
        