apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: myapp-pod
  labels: 
    app: myapp
spec:
  selector: 
    matchLabels:
      app: student
  replicas: 1
  template:
    metadata:
      name: myapp-pod
      labels:
        app: student
    spec:
      containers:
      - name: studentapp
        imagePullPolicy: IfNotPresent
        image: student
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /home
            port: 8000
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /students
            port: 8000
        ports:
        - containerPort: 8000
        